import { Router } from 'express';
import { announcementsRoutes } from '../modules/announcements/announcements.routes';
import { apartmentsRoutes } from '../modules/apartments/apartments.routes';
import { auditRoutes } from '../modules/audit/audit.routes';
import { authRoutes } from '../modules/auth/auth.routes';
import { buildingsRoutes } from '../modules/buildings/buildings.routes';
import { chatRoutes } from '../modules/chat/chat.routes';
import { complaintsRoutes } from '../modules/complaints/complaints.routes';
import { contractsRoutes } from '../modules/contracts/contracts.routes';
import { dashboardRoutes } from '../modules/dashboard/dashboard.routes';
import { documentsRoutes } from '../modules/documents/documents.routes';
import { expensesRoutes } from '../modules/expenses/expenses.routes';
import { invoicesRoutes } from '../modules/invoices/invoices.routes';
import { maintenanceRoutes } from '../modules/maintenance/maintenance.routes';
import { notificationsRoutes } from '../modules/notifications/notifications.routes';
import { paymentsRoutes } from '../modules/payments/payments.routes';
import { reportsRoutes } from '../modules/reports/reports.routes';
import { residentsRoutes } from '../modules/residents/residents.routes';
import { searchRoutes } from '../modules/search/search.routes';
import { securityRoutes } from '../modules/security/security.routes';
import { usersRoutes } from '../modules/users/users.routes';
import { visitorsRoutes } from '../modules/visitors/visitors.routes';

export const apiRouter = Router();

apiRouter.use('/auth', authRoutes);
apiRouter.use('/users', usersRoutes);
apiRouter.use('/buildings', buildingsRoutes);
apiRouter.use('/apartments', apartmentsRoutes);
apiRouter.use('/residents', residentsRoutes);
apiRouter.use('/contracts', contractsRoutes);
apiRouter.use('/invoices', invoicesRoutes);
apiRouter.use('/payments', paymentsRoutes);
apiRouter.use('/expenses', expensesRoutes);
apiRouter.use('/maintenance', maintenanceRoutes);
apiRouter.use('/complaints', complaintsRoutes);
apiRouter.use('/visitors', visitorsRoutes);
apiRouter.use('/security', securityRoutes);
apiRouter.use('/announcements', announcementsRoutes);
apiRouter.use('/notifications', notificationsRoutes);
apiRouter.use('/documents', documentsRoutes);
apiRouter.use('/chat', chatRoutes);
apiRouter.use('/reports', reportsRoutes);
apiRouter.use('/dashboard', dashboardRoutes);
apiRouter.use('/search', searchRoutes);
apiRouter.use('/audit', auditRoutes);
